#!/usr/bin/with-contenv bash

cd /data

if [[ -z ${STARTUP_PARAMETER} ]];then
  echo "No startup parameter specified. Using -cli"
  exec \
    s6-setuidgid grfd \
      /usr/bin/java -Dlog4j2.formatMsgNoLookups=true -jar \
        /app/serverpackcreator/serverpackcreator.jar -cli
else
  echo "Specified startup parameter -$STARTUP_PARAMETER"
  exec \
    s6-setuidgid grfd \
      /usr/bin/java -Dlog4j2.formatMsgNoLookups=true -jar \
        /app/serverpackcreator/serverpackcreator.jar "-${STARTUP_PARAMETER}"
fi