/* Copyright (C) 2026 Griefed
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 *
 * The full license can be found at https:github.com/Griefed/ServerPackCreator/blob/main/LICENSE
 */
package de.griefed.serverpackcreator.grinder.loader

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

/**
 * Pins [InstallFailureDiagnosis] against the console of a real failed install (2026-08-23,
 * `1.20.4-Forge-49.0.8`). The failure reporting used to print `output.lines.takeLast(25)`, and this
 * console is exactly the shape that defeats: the cause is three `Permission denied` lines near the
 * *top*, and the last 25 lines carry only the JVM's downstream `@argfile` complaint, which points at
 * the start-script template rather than at the mount.
 */
internal class InstallFailureDiagnosisTest {

    /** The real console, trimmed of the parts that carry no signal either way. */
    private val realFailedInstall = listOf(
        "Start script generated by ServerPackCreator dev.",
        "Detected 1.20.4 - Java 17",
        "start.sh: line 568: ./.previousrun: Permission denied",
        "server.jar could not be found.",
        "Downloading server.jar",
        "Warning: Failed to open the file ./server.jar: Permission denied",
        "curl: (23) Failure writing output to destination",
        "Generating user_jvm_args.txt from variables...",
        "start.sh: line 206: user_jvm_args.txt: Permission denied",
        "Starting server...",
        "Java version:",
        "openjdk version \"17.0.20.1\" 2026-08-18",
        "Error: could not open `user_jvm_args.txt'",
        "Exiting..."
    )

    @Test
    fun namesTheUnwritableMountRatherThanTheDownstreamJvmError() {
        val diagnosis = InstallFailureDiagnosis.of(realFailedInstall)

        Assertions.assertNotNull(diagnosis, "a console full of Permission denied must be diagnosed")
        Assertions.assertTrue(
            diagnosis!!.contains("write", ignoreCase = true),
            "the diagnosis must say the container could not write; was: $diagnosis"
        )
        Assertions.assertTrue(
            diagnosis.contains(de.griefed.serverpackcreator.grinder.container.ContainerUser.ENV_KEY),
            "the diagnosis must name the knob that fixes it; was: $diagnosis"
        )
    }

    @Test
    fun quotesTheEvidenceEvenWhenItSitsFarOutsideTheReportedTail() {
        // 200 lines of noise after the cause: the old takeLast(25) window would have dropped it entirely.
        val buried = realFailedInstall + (1..200).map { "[Server thread/INFO]: noise $it" }

        val diagnosis = InstallFailureDiagnosis.of(buried)

        Assertions.assertNotNull(diagnosis)
        Assertions.assertTrue(
            diagnosis!!.contains("./.previousrun") || diagnosis.contains("user_jvm_args.txt"),
            "the diagnosis must quote an offending line as evidence; was: $diagnosis"
        )
    }

    @Test
    fun staysSilentOnAConsoleItCannotExplain() {
        val unexplained = listOf(
            "Start script generated by ServerPackCreator dev.",
            "Downloading server.jar",
            "curl: (6) Could not resolve host: github.com"
        )

        Assertions.assertNull(
            InstallFailureDiagnosis.of(unexplained),
            "guessing a cause is worse than the raw tail — only diagnose what is actually recognisable"
        )
    }
}
