#!/usr/bin/env fish
############################################LICENSE#################################################
# Copyright (C) 2026 Griefed
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
#
# The full license can be found at https:github.com/Griefed/ServerPackCreator/blob/main/LICENSE
############################################DESCRIPTION#################################################
#
# This script uses Jabba to download and install Java with the version required by the Minecraft version set in the
# variables.txt which was also shipped with this modpack. Should you want to use a different Java version with your
# server pack, change the RECOMMENDED_JAVA_VERSION. Likewise, you can change the vendor of the JDK to another one by
# changing JDK_VENDOR in your variables.txt
#
# Depending on which Minecraft version is used in this server pack, a different Java version may be installed.
#
# A list of available JDK versions and vendors can be found at https://github.com/Jabba-Team/index/blob/main/index.json
# Jabba is available at https://github.com/Jabba-Team/jabba
#
############################################NOTES#################################################
# Java Install script generated by ServerPackCreator SPC_SERVERPACKCREATOR_VERSION_SPC.
# The template which was used in the generation of this script can be found at:
#   https://github.com/Griefed/ServerPackCreator/blob/SPC_SERVERPACKCREATOR_VERSION_SPC/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_java_template.fish
#
# This is the fish-shell counterpart to default_java_template.sh. Fish and bash are incompatible
# shell languages, not syntax variants of one another, so this script is a standalone rewrite,
# not a sourced/shared file. Run it with `./default_java_template.fish` or `fish default_java_template.fish`.
#
# Depending on which Minecraft version is used in this server pack, a different Java version may be installed.
#
# ATTENTION:
#   This script will NOT modify the JAVA_HOME variable for your user.
# ATTENTION:
#   Assumes fish >= 3.4 (uses `string split -m`, `string trim -c`, `read -P`).

# commandAvailable command
# Check whether the command $argv[1] is available for execution. Can be used in if-statements.
function commandAvailable
    command -v "$argv[1]" >/dev/null 2>&1
end

# loadVariables path
# Parses a simple KEY=VALUE (optionally "quoted") file -- the same format ServerPackCreator
# writes to variables.txt and to .previousrun -- and exports each entry as a fish global.
# Comments (#) and blank lines are skipped. This exists because fish cannot `source` a
# bash-syntax KEY=VALUE file directly (bare `VAR=value` is not valid fish).
function loadVariables --argument-names path
    while read -l line
        set -l trimmed (string trim -- $line)

        if test -z "$trimmed"
            continue
        end
        if string match -q '#*' -- $trimmed
            continue
        end

        set -l parts (string split -m1 "=" -- $trimmed)
        if test (count $parts) -ne 2
            continue
        end

        set -l key $parts[1]
        set -l value (string trim -c '"' -- $parts[2])
        set -gx $key $value
    end < $path
end

# installJabba
# Downloads and installs Jabba, the software used to download and install Java for the Minecraft server.
function installJabba
    echo "Downloading and installing jabba."
    # install.sh is itself a bash script and is always run via `bash`, regardless of the calling
    # shell -- that part doesn't change. What changes for fish is what we source afterwards:
    # install.sh generates BOTH ~/.jabba/jabba.sh (bash) and ~/.jabba/jabba.fish (fish) when it
    # detects fish is present on the system, per the Jabba README's own documented fish snippet:
    #   curl -sL <install.sh> | bash; and . ~/.jabba/jabba.fish
    # jabba.sh is bash `export VAR=value` syntax and is not valid fish, so we must source
    # jabba.fish here, not jabba.sh.
    if commandAvailable curl
        curl -sL $JABBA_INSTALL_URL_SH | bash
        and source ~/.jabba/jabba.fish
    else if commandAvailable wget
        wget -qO- $JABBA_INSTALL_URL_SH | bash
        and source ~/.jabba/jabba.fish
    else
        echo "[ERROR] wget or curl is required to install jabba."
        exit 1
    end

    if test -s "$JABBA_HOME/jabba.fish"
        source "$JABBA_HOME/jabba.fish"
    end
end

if not test -s "variables.txt"
    echo "ERROR! variables.txt not present. Without it the server can not be installed, configured or started."
    exit 1
end

loadVariables "./variables.txt"

# if ldd is not available, we may be on MacOS
if commandAvailable ldd
    set -l GBLIC_VERSION (ldd --version | awk '/ldd/{print $NF}')
    set -l GBLIC_SEMANTICS (string split "." -- $GBLIC_VERSION)

    # Older Linux systems aren't supported, sadly. This mainly affects Ubuntu 20 and Linux distributions from around that time
    # which use glibc versions older than 2.32 & 2.34.
    # NOTE: fish arrays are 1-indexed. Bash's ${GBLIC_SEMANTICS[1]} (minor version) is $GBLIC_SEMANTICS[2] here.
    if test $GBLIC_SEMANTICS[2] -lt 32
        echo "Jabba only supports systems with glibc 2.32 & 2.34 onward. You have $GBLIC_VERSION. Automated Java installation can not proceed."
        echo "DO NOT ATTEMPT TO UPDATE OR UPGRADE YOUR INSTALLED VERSION OF GLIBC! DOING SO MAY CORRUPT YOUR ENTIRE SYSTEM!"
        echo "Instead, consider upgrading to a newer version of your OS. Example: In case of Ubuntu 20 LTS, consider upgrading to 22 LTS or 24 LTS."
        echo ""
        echo "If that is not an option, you will have to install the required Java version on your system manually, the old fashioned way."
        echo "Your variables.txt says you require: $JDK_VENDOR@$RECOMMENDED_JAVA_VERSION"
        echo "When you installed said Java version, 'SKIP_JAVA_CHECK=true' in the variables.txt and run the start-script again."
        exit 1
    end
end

set -gx JABBA_VERSION $JABBA_INSTALL_VERSION

if test -s ~/.jabba/jabba.fish
    source ~/.jabba/jabba.fish
else if not commandAvailable jabba
    echo "Automated Java installation requires a piece of Software called 'Jabba'."
    echo "Type 'I agree' if you agree to the installation of the aforementioned software."
    read -P "Response: " ANSWER

    if test "$ANSWER" = "I agree"
        installJabba
    else
        echo "User did not agree to Jabba installation. Aborting Java installation process."
        exit 1
    end
end

echo "Downloading and using Java $JDK_VENDOR@$RECOMMENDED_JAVA_VERSION"
jabba install "$JDK_VENDOR@$RECOMMENDED_JAVA_VERSION"
jabba use "$JDK_VENDOR@$RECOMMENDED_JAVA_VERSION"

echo "Installation finished. Returning to start-script."
