#!/usr/bin/env fish
############################################LICENSE#################################################
# Copyright (C) 2026 Griefed
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
#
# The full license can be found at https:github.com/Griefed/ServerPackCreator/blob/main/LICENSE
############################################DESCRIPTION#################################################
#
# Start script to easily run your server pack. In order to run this script even easier, run the start.bat-file
# which was also shipped with this server pack.
#
# A start-script supporting Forge, NeoForge, Fabric, Quilt and LegacyFabric as well as their supported Minecraft
# versions.
#
# This script downloads and installs the Modloader server depending on the settings in the acompanying variables.txt
# which was also shipped with this server pack. Should no suitable Java installation be found and your $JAVA-variable
# be set to "java", then a suitable Java-installation will also be downloaded and provided to this server pack.
#
# You can let the server restart by setting RESTART to true in your variables.txt. More information about the
# various settings in said file. Go check it out.
#
############################################NOTES#################################################
#
# Start script generated by ServerPackCreator SPC_SERVERPACKCREATOR_VERSION_SPC.
# The template which was used in the generation of this script can be found at:
#   https://github.com/Griefed/ServerPackCreator/blob/SPC_SERVERPACKCREATOR_VERSION_SPC/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.fish
#
# This is the fish-shell counterpart to default_template.sh. Fish and bash are incompatible shell
# languages, not syntax variants of one another, so this script is a standalone rewrite, not a
# sourced/shared file. Run it with `./default_template.fish` or `fish default_template.fish`.
# It expects `install_java.fish` (the fish counterpart to install_java.sh) alongside it.
#
# Depending on which modloader is set, different checks are run to ensure the server will start accordingly.
# If the modloader checks and setup are passed, Minecraft and EULA checks are run.
# If everything is in order, the server is started.
#
# Depending on the Minecraft version you will require a different Java version to run the server.
#   1.16.5 and older requires Java 8 (Java 11 will run better and work with 99% of mods, give it a try)
#     Linux:
#       You may acquire a Java 8 install here: https://adoptium.net/temurin/releases/?variant=openjdk8&version=8&package=jdk&arch=x64&os=linux
#       You may acquire a java 11 install here: https://adoptium.net/temurin/releases/?variant=openjdk11&version=11&package=jdk&arch=x64&os=linux
#     macOS:
#       You may acquire a Java 8 install here: https://adoptium.net/temurin/releases/?variant=openjdk8&version=8&package=jdk&arch=x64&os=mac
#       You may acquire a java 11 install here: https://adoptium.net/temurin/releases/?variant=openjdk11&version=11&package=jdk&arch=x64&os=mac
#   1.18.2 and newer requires Java 17 (Java 18 will run better and work with 99% of mods, give it a try)
#     Linux:
#       You may acquire a Java 17 install here: https://adoptium.net/temurin/releases/?variant=openjdk17&version=17&package=jdk&arch=x64&os=linux
#       You may acquire a Java 18 install here: https://adoptium.net/temurin/releases/?variant=openjdk18&version=18&package=jdk&arch=x64&os=linux
#     macOS:
#       You may acquire a Java 17 install here: https://adoptium.net/temurin/releases/?variant=openjdk17&version=17&package=jdk&arch=x64&os=mac
#       You may acquire a Java 18 install here: https://adoptium.net/temurin/releases/?variant=openjdk18&version=18&package=jdk&arch=x64&os=mac
#   1.20.5 and newer require Java 21
#     Linux:
#       You may acquire a Java 21 install here: https://adoptium.net/temurin/releases/?variant=openjdk21&version=21&package=jdk&arch=x64&os=linux
#     macOS:
#       You may acquire a Java 21 install here: https://adoptium.net/temurin/releases/?variant=openjdk21&version=21&package=jdk&arch=x64&os=mac
#
# ATTENTION:
#   Assumes fish >= 3.4 (uses `string split -m`, `string trim -c`, `read -P`, `read --nchars`).

# pause
# Pause script execution. User input in the form of any keyboard key-press is required to continue execution.
function pause
    read -s -n 1 -P "Press any key to continue" _discard
end

# crashServer reason
# Crash script execution with exit code 1. Print $argv[1] to the console.
function crashServer
    echo "$argv[1]"
    pause
    exit 1
end

# commandAvailable command
# Check whether the command $argv[1] is available for execution. Can be used in if-statements.
function commandAvailable
    command -v "$argv[1]" >/dev/null 2>&1
end

# loadVariables path
# Parses a simple KEY=VALUE (optionally "quoted") file -- the same format ServerPackCreator writes
# to variables.txt and to .previousrun -- and exports each entry as a fish global. Comments (#) and
# blank lines are skipped. This exists because fish cannot `source` a bash-syntax KEY=VALUE file
# directly (bare `VAR=value` is not valid fish).
function loadVariables --argument-names path
    while read -l line
        set -l trimmed (string trim -- $line)

        if test -z "$trimmed"
            continue
        end
        if string match -q '#*' -- $trimmed
            continue
        end

        set -l parts (string split -m1 "=" -- $trimmed)
        if test (count $parts) -ne 2
            continue
        end

        set -l key $parts[1]
        set -l value (string trim -c '"' -- $parts[2])
        set -gx $key $value
    end < $path
end

# getJavaVersion
# Set $JAVA_VERSION by checking $JAVA using -fullversion. Only the major version is stored, e.g. 8, 11, 17, 21.
function getJavaVersion
    set -g JAVA_VERSION ("$JAVA" -fullversion 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    if test "$JAVA_VERSION" -eq 1
        set -g JAVA_VERSION ("$JAVA" -fullversion 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f2)
    end
end

# installJava
# Runs the companion-script "install_java.fish" to install the required Java version for this modded Minecraft server.
function installJava
    echo "No suitable Java installation was found on your system. Proceeding to Java installation."
    if not source install_java.fish
        crashServer "Java install-script failed. Install Java $RECOMMENDED_JAVA_VERSION manually or edit JAVA in your variables.txt to point to a Java installation of said version."
    end
    if not commandAvailable "$JAVA"
        crashServer "Java installation failed. Couldn't find $JAVA."
    end
end

# downloadIfNotExist fileToCheck fileToDownload downloadURL
# Checks whether file $argv[1] exists. If not, then it is downloaded from $argv[3] and stored as
# $argv[2]. Prints "true"/"false" to stdout so callers can capture it via command substitution.
function downloadIfNotExist --argument-names fileToCheck fileToDownload downloadURL
    if not test -s "$fileToCheck"
        echo "$fileToCheck could not be found." >&2
        echo "Downloading $fileToDownload" >&2
        echo "from $downloadURL" >&2

        if commandAvailable curl
            curl -# -L -o "./$fileToDownload" "$downloadURL"
        else if commandAvailable wget
            wget --show-progress -O "./$fileToDownload" "$downloadURL"
        else
            crashServer "[ERROR] wget or curl is required to download files."
        end

        if test -s "$fileToDownload"
            echo "Download complete." >&2
            echo "true"
        else
            echo "false"
        end
    else
        echo "$fileToCheck present." >&2
        echo "false"
    end
end

# runJavaCommand command
# Runs the command $argv[1] using the Java installation set in $JAVA.
# NOTE: bash's original does an intentionally-unquoted `"$JAVA" ${1}` so the string gets
# word-split into separate argv entries. Fish does NOT word-split unquoted variables, so that
# trick doesn't translate directly -- we split explicitly on spaces instead. `--no-empty` drops
# empty tokens (e.g. from an empty $JAVA_ARGS producing a double space), matching bash's
# word-splitting -- otherwise Java receives a stray "" argument and reads it as the main class
# ("Could not find or load main class").
function runJavaCommand --argument-names cmd
    set -l args (string split --no-empty " " -- $cmd)
    "$JAVA" $args
end

# runInstallerJavaCommand command
# Runs a modloader *installer* with $JAVA_INSTALLER when that is set in the variables.txt, otherwise
# with $JAVA. Some installers need a newer Java than the server they install: the Quilt installer
# requires Java 17+, while e.g. Minecraft 1.16.1 must run on Java 8 -- one JDK cannot satisfy both.
# Leave JAVA_INSTALLER unset and nothing changes; set it to a Java 17+ binary to install such a loader.
function runInstallerJavaCommand --argument-names cmd
    set -l args (string split --no-empty " " -- $cmd)
    if set -q JAVA_INSTALLER; and test -n "$JAVA_INSTALLER"
        "$JAVA_INSTALLER" $args
    else
        "$JAVA" $args
    end
end

# refreshServerJar
# Refresh the ServerStarterJar used for running Forge and NeoForge servers.
function refreshServerJar
    if test "$SERVERSTARTERJAR_FORCE_FETCH" = "true"
        rm -f server.jar
    end

    if test "$SERVERSTARTERJAR_VERSION" = "latest"
        set -g SERVERSTARTERJAR_DOWNLOAD_URL "https://github.com/neoforged/ServerStarterJar/releases/latest/download/server.jar"
    else
        set -g SERVERSTARTERJAR_DOWNLOAD_URL "https://github.com/neoforged/ServerStarterJar/releases/download/$SERVERSTARTERJAR_VERSION/server.jar"
    end

    downloadIfNotExist "server.jar" "server.jar" "$SERVERSTARTERJAR_DOWNLOAD_URL" >/dev/null
end

# cleanServerFiles
# Clean up files created by installers or modloader servers, but leave server pack files untouched.
function cleanServerFiles
    set -l FILES_TO_REMOVE (string split "," -- $CLEANUP)
    for FILE_TO_REMOVE in $FILES_TO_REMOVE
        # FILE_TO_REMOVE may be a literal filename (e.g. "server.jar") or a glob pattern
        # (e.g. "*installer.jar"). Fish, unlike bash, never glob-expands the *contents* of a
        # variable even when unquoted -- wildcard characters are only expanded when written
        # literally in the command line. `find -name` does the pattern matching itself against
        # the current directory (non-recursive, matching the original intent), handling both
        # literal names and glob patterns uniformly.
        for MATCH in (find . -maxdepth 1 -mindepth 1 -name "$FILE_TO_REMOVE")
            rm -r -v "$MATCH" 2>/dev/null
            and echo "Deleted $MATCH"
        end
    end
end

# forgeNeedsItsOwnArgfile
# Whether the ServerStarterJar must be bypassed for this Minecraft version, because it cannot launch the Forge
# install produced for it. Returns success (0) when the pack has to start Forge from Forge's own argfile.
#
# Forge's installer writes one of two argfiles, and the ServerStarterJar can only start one of them:
#   * Minecraft 1.17 .. 1.20.1  -> "-p <module path>" over cpw's securejarhandler. The starter jar synthesises a
#                                  boot layer for that module path, and cpw's loader falls back to the platform
#                                  classloader for anything it cannot place, so this works.
#   * Minecraft 1.20.2          -> "-p <module path> --add-modules ALL-MODULE-PATH" over Forge's OWN securemodules
#                                  fork, which instead THROWS "Could not find parent layer for module `java.base`"
#                                  from SecureModuleClassLoader before the server starts. No shim jar exists here.
#   * Minecraft 1.20.3 onwards  -> "-jar forge-<version>-shim.jar". The starter jar takes its own "jar mode" and
#                                  never synthesises a layer, so this works again -- verified through Minecraft
#                                  1.21.1, which reaches the ready-line through the starter jar.
#
# 1.20.3 is bypassed with 1.20.2 even though it ships the shim: it is documented as affected in HELP.md, it has
# two Forge builds in total, and over-including it costs only the starter jar's hosting-company compatibility
# while under-including it costs a server that cannot start.
#
# The MAJOR is part of the test on purpose. Minor and patch carry this meaning only under the 1.x scheme:
# Minecraft 26.20.2 matches 1.20.2 component for component below the major, and bypassing the starter jar there
# would quietly drop that compatibility for every modern pack.
#
# NOTE: fish arrays are 1-indexed. Bash's ${SEMANTICS[0]} (major) is $SEMANTICS[1] here, ${SEMANTICS[1]} (minor)
# is $SEMANTICS[2] and ${SEMANTICS[2]} (patch) is $SEMANTICS[3].
function forgeNeedsItsOwnArgfile
    # Screen every component before comparing it, and take the bypass for anything unreadable -- comparing a
    # non-numeric component is an error, and the bypass is the route that works for every Forge from 1.17 on.
    if not string match -qr '^[0-9]+$' -- "$SEMANTICS[1]"
        return 0
    end
    if not string match -qr '^[0-9]+$' -- "$SEMANTICS[2]"
        return 0
    end
    if not test "$SEMANTICS[1]" -eq 1
        return 1
    end
    if not test "$SEMANTICS[2]" -eq 20
        return 1
    end
    if test (count $SEMANTICS) -lt 3
        return 1
    end
    if not string match -qr '^[0-9]+$' -- "$SEMANTICS[3]"
        return 0
    end
    if test "$SEMANTICS[3]" -eq 2; or test "$SEMANTICS[3]" -eq 3
        return 0
    end
    return 1
end

# setupForge
# Download and install a Forge server for $MODLOADER_VERSION.
function setupForge
    echo ""
    echo "Running Forge checks and setup..."
    set -g FORGE_INSTALLER_URL "https://files.minecraftforge.net/maven/net/minecraftforge/forge/$MINECRAFT_VERSION-$MODLOADER_VERSION/forge-$MINECRAFT_VERSION-$MODLOADER_VERSION-installer.jar"
    set -g FORGE_JAR_LOCATION "do_not_manually_edit"

    # NOTE: fish arrays are 1-indexed. Bash's ${SEMANTICS[0]} (major) is $SEMANTICS[1] here, and its
    # ${SEMANTICS[1]} (minor) is $SEMANTICS[2].
    # Forge changed how a server is launched: up to Minecraft 1.16 the installer produced a runnable forge.jar, from
    # 1.17 it produces libraries/.../unix_args.txt instead. The major must be checked too, because the minor alone only
    # carries that meaning under the 1.x scheme -- Minecraft 26.2 has minor 2, which would otherwise read as the 1.2
    # era and take the legacy path, where the server dies with "Unable to access jarfile forge.jar".
    # Screened before compared, as in forgeNeedsItsOwnArgfile: comparing a non-numeric component is an error.
    if string match -qr '^[0-9]+$' -- "$SEMANTICS[1]"; and string match -qr '^[0-9]+$' -- "$SEMANTICS[2]"; and test $SEMANTICS[1] -eq 1; and test $SEMANTICS[2] -le 16
        set -g FORGE_JAR_LOCATION "forge.jar"
        set -g LAUNCHER_JAR_LOCATION "forge.jar"
        set -g SERVER_RUN_COMMAND "$JAVA_ARGS -jar $LAUNCHER_JAR_LOCATION nogui"

        if test (downloadIfNotExist "$FORGE_JAR_LOCATION" "forge-installer.jar" "$FORGE_INSTALLER_URL") = "true"
            echo "Forge Installer downloaded. Installing..."
            runJavaCommand "-jar forge-installer.jar --installServer"

            echo "Renaming forge-$MINECRAFT_VERSION-$MODLOADER_VERSION.jar to forge.jar"
            mv "forge-$MINECRAFT_VERSION-$MODLOADER_VERSION.jar" forge.jar
            mv "forge-$MINECRAFT_VERSION-$MODLOADER_VERSION-universal.jar" forge.jar

            if test -s "$FORGE_JAR_LOCATION"
                rm -f forge-installer.jar
                echo "Installation complete. forge-installer.jar deleted."
            else
                rm -f forge-installer.jar
                crashServer "Something went wrong during the server installation. Please try again in a couple of minutes and check your internet connection."
            end
        end
    else
        if test "$USE_SSJ" = "false"
            set -g FORGE_JAR_LOCATION "libraries/net/minecraftforge/forge/$MINECRAFT_VERSION-$MODLOADER_VERSION/forge-$MINECRAFT_VERSION-$MODLOADER_VERSION-server.jar"
            set -g SERVER_RUN_COMMAND "@user_jvm_args.txt @libraries/net/minecraftforge/forge/$MINECRAFT_VERSION-$MODLOADER_VERSION/unix_args.txt nogui"
            if test (downloadIfNotExist "$FORGE_JAR_LOCATION" "forge-installer.jar" "$FORGE_INSTALLER_URL") = "true"
                echo "Forge Installer downloaded. Installing..."
                runJavaCommand "-jar forge-installer.jar --installServer"
            end
        else
            # SSJ_FORGE_ARGS defaults to -Djava.security.manager=allow, which JEP 486 made fatal from Java 24 on:
            # the VM refuses to start rather than ignoring it. Minecraft 26.x requires Java 25, so passing it there
            # breaks every modern Forge pack before Forge loads. Keep it where it is needed, drop it where it kills.
            #
            # That flag is not cosmetic to SSJ: it runs the Forge installer inside its own JVM and needs a
            # SecurityManager to swallow the System.exit(0) the installer calls when it is done. Without it the
            # installer's exit ends the whole process -- the pack installs, reports success, exits 0, and never
            # launches the server. So on Java that cannot trap the exit we do not hand SSJ the install at all:
            # install here, then launch from the argfile the installer produces, as the USE_SSJ=false path does.
            # Fail-safe: only a Java we can read AND that predates 24 may use the ServerStarterJar path.
            # Second reason, independent of Java: Minecraft 1.20.2/1.20.3 Forge cannot be launched by the
            # ServerStarterJar at all -- see forgeNeedsItsOwnArgfile above.
            set -l SSJ_REFUSAL ""
            if not string match -qr '^[0-9]+$' -- "$JAVA_VERSION"; or test "$JAVA_VERSION" -ge 24
                set SSJ_REFUSAL "Java $JAVA_VERSION cannot grant ServerStarterJar the Security Manager it needs to run the Forge installer"
            else if forgeNeedsItsOwnArgfile
                set SSJ_REFUSAL "Forge for Minecraft $MINECRAFT_VERSION starts from a module-path argfile the ServerStarterJar cannot launch"
            end

            if test -n "$SSJ_REFUSAL"
                echo "$SSJ_REFUSAL,"
                echo "so this pack installs Forge directly and starts it from its argfile instead."
                set -g FORGE_ARGS_FILE "libraries/net/minecraftforge/forge/$MINECRAFT_VERSION-$MODLOADER_VERSION/unix_args.txt"
                set -g SERVER_RUN_COMMAND "@user_jvm_args.txt @$FORGE_ARGS_FILE nogui"
                if test (downloadIfNotExist "$FORGE_ARGS_FILE" "forge-installer.jar" "$FORGE_INSTALLER_URL") = "true"
                    echo "Forge Installer downloaded. Installing..."
                    runJavaCommand "-jar forge-installer.jar --installServer"
                end
            else
                set -g SERVER_RUN_COMMAND "@user_jvm_args.txt $SSJ_FORGE_ARGS -jar server.jar --installer-force --installer $FORGE_INSTALLER_URL nogui"
                refreshServerJar
            end
        end

        echo "Generating user_jvm_args.txt from variables..."
        echo "Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!"
        echo "Manually made changes to user_jvm_args.txt will be lost in the nether!"
        rm -f user_jvm_args.txt
        begin
            echo "# Xmx and Xms set the maximum and minimum RAM usage, respectively."
            echo "# They can take any number, followed by an M or a G."
            echo "# M means Megabyte, G means Gigabyte."
            echo "# For example, to set the maximum to 3GB: -Xmx3G"
            echo "# To set the minimum to 2.5GB: -Xms2500M"
            echo "# A good default for a modded server is 4GB."
            echo "# Uncomment the next line to set it."
            echo "# -Xmx4G"
            echo "$JAVA_ARGS"
        end >>user_jvm_args.txt
    end
end

# setupNeoForge
# Download and install a NeoForge server for $MODLOADER_VERSION.
function setupNeoForge
    echo ""
    echo "Running NeoForge checks and setup..."
    echo "Generating user_jvm_args.txt from variables..."
    echo "Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!"
    echo "Manually made changes to user_jvm_args.txt will be lost in the nether!"
    rm -f user_jvm_args.txt
    begin
        echo "# Xmx and Xms set the maximum and minimum RAM usage, respectively."
        echo "# They can take any number, followed by an M or a G."
        echo "# M means Megabyte, G means Gigabyte."
        echo "# For example, to set the maximum to 3GB: -Xmx3G"
        echo "# To set the minimum to 2.5GB: -Xms2500M"
        echo "# A good default for a modded server is 4GB."
        echo "# Uncomment the next line to set it."
        echo "# -Xmx4G"
        echo "$JAVA_ARGS"
    end >>user_jvm_args.txt

    # NOTE: fish arrays are 1-indexed. Bash's ${SEMANTICS[1]} (minor) is $SEMANTICS[2];
    # ${SEMANTICS[2]} (patch) is $SEMANTICS[3] here.
    set -l patch_ok 0
    if test (count $SEMANTICS) -eq 2; or test $SEMANTICS[3] -eq 1
        set patch_ok 1
    end

    # The major is part of the test because "minor is 20" only means the 1.20 era under the 1.x scheme: a future
    # Minecraft 26.20 would otherwise be sent at a 1.20-era URL that does not exist for it.
    if test $SEMANTICS[1] -eq 1; and test $SEMANTICS[2] -eq 20; and test $patch_ok -eq 1
        set -g SERVER_RUN_COMMAND "@user_jvm_args.txt -jar server.jar --installer-force --installer https://maven.neoforged.net/releases/net/neoforged/forge/$MINECRAFT_VERSION-$MODLOADER_VERSION/forge-$MINECRAFT_VERSION-$MODLOADER_VERSION-installer.jar nogui"
    else
        set -g SERVER_RUN_COMMAND "@user_jvm_args.txt -jar server.jar --installer-force --installer $MODLOADER_VERSION nogui"
    end

    refreshServerJar
end

# setupFabric
# Download and install a Fabric server for $MODLOADER_VERSION.
function setupFabric
    echo ""
    echo "Running Fabric checks and setup..."

    set -g FABRIC_INSTALLER_URL "https://maven.fabricmc.net/net/fabricmc/fabric-installer/$FABRIC_INSTALLER_VERSION/fabric-installer-$FABRIC_INSTALLER_VERSION.jar"
    set -g FABRIC_CHECK_URL "https://meta.fabricmc.net/v2/versions/loader/$MINECRAFT_VERSION/$MODLOADER_VERSION/server/json"
    set -g IMPROVED_FABRIC_LAUNCHER_URL "https://meta.fabricmc.net/v2/versions/loader/$MINECRAFT_VERSION/$MODLOADER_VERSION/$FABRIC_INSTALLER_VERSION/server/jar"

    # An already-installed launcher needs neither a check nor a download. This must come FIRST: the checks below
    # ask the network, and a failed request is indistinguishable from "Fabric does not support this version" —
    # which made a complete, ready-to-run pack refuse to start whenever it had no internet.
    if test -s "fabric-server-launcher.jar"
        echo "fabric-server-launcher.jar present. Moving on..."
        set -g LAUNCHER_JAR_LOCATION "fabric-server-launcher.jar"
    else if test -s "fabric-server-launch.jar"
        echo "fabric-server-launch.jar present. Moving on..."
        set -g LAUNCHER_JAR_LOCATION "fabric-server-launch.jar"
    else
        if commandAvailable curl
            set -g FABRIC_AVAILABLE (curl -LI "$FABRIC_CHECK_URL" -o /dev/null -w '%{http_code}\n' -s)
        else if commandAvailable wget
            set -g FABRIC_AVAILABLE (wget --spider --server-response "$FABRIC_CHECK_URL" 2>&1 | awk '/^  HTTP/{print $2}')
        end

        if commandAvailable curl
            set -g IMPROVED_FABRIC_LAUNCHER_AVAILABLE (curl -LI "$IMPROVED_FABRIC_LAUNCHER_URL" -o /dev/null -w '%{http_code}\n' -s)
        else if commandAvailable wget
            set -g IMPROVED_FABRIC_LAUNCHER_AVAILABLE (wget --spider --server-response "$IMPROVED_FABRIC_LAUNCHER_URL" 2>&1 | awk '/^  HTTP/{print $2}')
        end

        if test "$IMPROVED_FABRIC_LAUNCHER_AVAILABLE" = "200"
            echo "Improved Fabric Server Launcher available..."
            echo "The improved launcher will be used to run this Fabric server."
            set -g LAUNCHER_JAR_LOCATION "fabric-server-launcher.jar"
            downloadIfNotExist "fabric-server-launcher.jar" "fabric-server-launcher.jar" "$IMPROVED_FABRIC_LAUNCHER_URL" >/dev/null
        else if test "$FABRIC_AVAILABLE" != "200"
            crashServer "Fabric is not available for Minecraft $MINECRAFT_VERSION, Fabric $MODLOADER_VERSION."
        else if test (downloadIfNotExist "fabric-server-launch.jar" "fabric-installer.jar" "$FABRIC_INSTALLER_URL") = "true"
            echo "Installer downloaded..."
            set -g LAUNCHER_JAR_LOCATION "fabric-server-launch.jar"
            runJavaCommand "-jar fabric-installer.jar server -mcversion $MINECRAFT_VERSION -loader $MODLOADER_VERSION -downloadMinecraft"

            if test -s "fabric-server-launch.jar"
                rm -rf .fabric-installer
                rm -f fabric-installer.jar
                echo "Installation complete. fabric-installer.jar deleted."
            else
                rm -f fabric-installer.jar
                crashServer "fabric-server-launch.jar not found. Maybe the Fabric servers are having trouble. Please try again in a couple of minutes and check your internet connection."
            end
        else
            echo "fabric-server-launch.jar present. Moving on..."
            set -g LAUNCHER_JAR_LOCATION "fabric-server-launch.jar"
        end
    end

    set -g SERVER_RUN_COMMAND "$JAVA_ARGS -jar $LAUNCHER_JAR_LOCATION nogui"
end

# setupQuilt
# Download and install a Quilt server for $MODLOADER_VERSION.
function setupQuilt
    echo ""
    echo "Running Quilt checks and setup..."

    set -g QUILT_INSTALLER_URL "https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-installer/$QUILT_INSTALLER_VERSION/quilt-installer-$QUILT_INSTALLER_VERSION.jar"
    set -g QUILT_CHECK_URL "https://meta.fabricmc.net/v2/versions/intermediary/$MINECRAFT_VERSION"

    if commandAvailable curl
        set -g QUILT_AVAILABLE (curl -sL "$QUILT_CHECK_URL")
    else if commandAvailable wget
        set -g QUILT_AVAILABLE (wget -qO- "$QUILT_CHECK_URL")
    end

    # The intermediary endpoint always responds 200, whether or not the requested Minecraft
    # version has a Quilt mapping -- unavailability shows up as an empty JSON array body, not
    # as an HTTP error. So we fetch the body (above) and compare its content, not a status code.
    if test "$QUILT_AVAILABLE" = "[]"
        crashServer "Quilt is not available for Minecraft $MINECRAFT_VERSION, Quilt $MODLOADER_VERSION."
    else if test (downloadIfNotExist "quilt-server-launch.jar" "quilt-installer.jar" "$QUILT_INSTALLER_URL") = "true"
        echo "Installer downloaded. Installing..."
        # The Quilt installer itself requires Java 17+, even when the server will run on an older Java.
        runInstallerJavaCommand "-jar quilt-installer.jar install server $MINECRAFT_VERSION --download-server --install-dir=."

        if test -s "quilt-server-launch.jar"
            rm quilt-installer.jar
            echo "Installation complete. quilt-installer.jar deleted."
        else
            rm -f quilt-installer.jar
            crashServer "quilt-server-launch.jar not found. The Quilt installer requires Java 17 or newer: if the message above says so, set JAVA_INSTALLER in your variables.txt to a Java 17+ binary (your server keeps running on JAVA). Otherwise the Quilt servers may be having trouble - try again in a couple of minutes and check your internet connection."
        end
    end

    # The vanilla server JAR, on its own terms rather than as a side effect of installing the launcher.
    # --download-server above runs only when quilt-server-launch.jar was missing, so a pack that kept its
    # launcher and lost the game JAR never fetches one and Quilt refuses to start. See the bash template.
    if not test -s "server.jar"
        echo "The Minecraft server JAR is missing. Fetching it with the Quilt installer..."
        downloadIfNotExist "quilt-installer.jar" "quilt-installer.jar" "$QUILT_INSTALLER_URL" >/dev/null
        runInstallerJavaCommand "-jar quilt-installer.jar install server $MINECRAFT_VERSION --download-server --install-dir=."
        rm -f quilt-installer.jar
        if not test -s "server.jar"
            crashServer "The Minecraft server JAR for $MINECRAFT_VERSION could not be downloaded. Without it Quilt Loader cannot launch. Check your internet connection and try again."
        end
    end

    set -g LAUNCHER_JAR_LOCATION "quilt-server-launch.jar"
    set -g SERVER_RUN_COMMAND "$JAVA_ARGS -jar $LAUNCHER_JAR_LOCATION nogui"
end

# setupLegacyFabric
# Download and install a LegacyFabric server for $MODLOADER_VERSION.
function setupLegacyFabric
    echo ""
    echo "Running LegacyFabric checks and setup..."

    set -g LEGACYFABRIC_INSTALLER_URL "https://maven.legacyfabric.net/net/legacyfabric/fabric-installer/$LEGACYFABRIC_INSTALLER_VERSION/fabric-installer-$LEGACYFABRIC_INSTALLER_VERSION.jar"
    set -g LEGACYFABRIC_CHECK_URL "https://meta.legacyfabric.net/v2/versions/loader/$MINECRAFT_VERSION"

    if commandAvailable curl
        set -g LEGACYFABRIC_AVAILABLE (curl -sL "$LEGACYFABRIC_CHECK_URL")
    else if commandAvailable wget
        set -g LEGACYFABRIC_AVAILABLE (wget -qO- "$LEGACYFABRIC_CHECK_URL")
    end

    if test "$LEGACYFABRIC_AVAILABLE" = "[]"
        crashServer "LegacyFabric is not available for Minecraft $MINECRAFT_VERSION, LegacyFabric $MODLOADER_VERSION."
    else if test (downloadIfNotExist "fabric-server-launch.jar" "legacyfabric-installer.jar" "$LEGACYFABRIC_INSTALLER_URL") = "true"
        echo "Installer downloaded. Installing..."
        runJavaCommand "-jar legacyfabric-installer.jar server -mcversion $MINECRAFT_VERSION -loader $MODLOADER_VERSION -downloadMinecraft"

        if test -s "fabric-server-launch.jar"
            rm legacyfabric-installer.jar
            echo "Installation complete. legacyfabric-installer.jar deleted."
        else
            rm -f legacyfabric-installer.jar
            crashServer "fabric-server-launch.jar not found. Maybe the LegacyFabric servers are having trouble. Please try again in a couple of minutes and check your internet connection."
        end
    end

    set -g LAUNCHER_JAR_LOCATION "fabric-server-launch.jar"
    set -g SERVER_RUN_COMMAND "$JAVA_ARGS -jar $LAUNCHER_JAR_LOCATION nogui"
end

echo "Start script generated by ServerPackCreator SPC_SERVERPACKCREATOR_VERSION_SPC."
echo "To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file."

# Resolve the directory containing this script, following symlinks -- fish equivalent of the
# BASH_SOURCE resolution loop (fish has no BASH_SOURCE; `status filename` is the closest analog).
set -l SOURCE (status filename)
while test -L "$SOURCE"
    set -l DIR (cd (dirname "$SOURCE"); and pwd)
    set SOURCE (readlink "$SOURCE")
    if not string match -q '/*' -- $SOURCE
        set SOURCE "$DIR/$SOURCE"
    end
end
set -l DIR (cd (dirname "$SOURCE"); and pwd)
cd "$DIR" >/dev/null 2>&1
or exit

# Check whether the path to this directory contains spaces. Spaces in the path are prone to cause trouble.
if string match -q '* *' -- $DIR
    echo "WARNING! The current location of this script contains spaces. This may cause this server to crash!"
    echo "It is strongly recommended to move this server pack to a location whose path does NOT contain SPACES!"
    echo ""
    echo "Current path:"
    echo "$PWD"
    echo ""
    read -P "Are you sure you want to continue? (Yes/No): " WHY

    if test "$WHY" = "Yes"
        echo "Alrighty. Prepare for unforseen consequences, Mr. Freeman..."
    else
        crashServer "User did not desire to run the server in a directory with spaces in its path."
    end
end

# It is not recommended to run the server using root as this introduces security risks to your system.
if test (id -u) = "0"
    echo "Warning! Running with administrator-privileges is not recommended."
end

if not test -s "variables.txt"
    crashServer "ERROR! variables.txt not present. Without it the server can not be installed, configured or started."
end

loadVariables "./variables.txt"

set -g LAUNCHER_JAR_LOCATION "do_not_manually_edit"
set -g SERVER_RUN_COMMAND "do_not_manually_edit"
set -g JAVA_VERSION "do_not_manually_edit"
set -g SEMANTICS (string split "." -- $MINECRAFT_VERSION)

# If Java checks are desired, then the available Java version is compared to the one required by the Minecraft server.
if test "$SKIP_JAVA_CHECK" = "true"
    echo "Skipping Java version checks."
else
    if test "$JAVA" = "java"
        if not commandAvailable "$JAVA"
            installJava
        else
            getJavaVersion
            if string match -qr '[0-9]+' -- "$JAVA_VERSION"
                if test "$JAVA_VERSION" != "$RECOMMENDED_JAVA_VERSION"
                    installJava
                end
            else
                installJava
            end
        end
    else
        getJavaVersion
        echo "Detected $SEMANTICS[1].$SEMANTICS[2].$SEMANTICS[3] - Java $JAVA_VERSION"
        if test "$JAVA_VERSION" != "$RECOMMENDED_JAVA_VERSION"
            set -g JAVA "java"
            installJava
        end
    end
end

# Resolve the version of the Java we are ACTUALLY going to use, whatever happened above -- checks skipped,
# a suitable Java found, or one just installed. Until here JAVA_VERSION can still be the
# do_not_manually_edit placeholder: installJava does not set it and neither does install_java.sh, so a pack
# that installs its own Java used to reach setupForge with no version at all. That is what let
# -Djava.security.manager=allow through to a Java 25 VM, which then refuses to start.
getJavaVersion

# Check and warn the user if a 32bit Java-installation is used.
"$JAVA" "-version" 2>&1 | grep -i "32-Bit"
and echo "WARNING! 32-Bit Java detected! It is highly recommended to use a 64-Bit version of Java!"

if test "$argv[1]" = "--cleanup"
    echo "Running cleanup..."
    cleanServerFiles
else if test -f "./.previousrun"
    loadVariables "./.previousrun"
    if test "$PREVIOUS_MINECRAFT_VERSION" != "$MINECRAFT_VERSION"; \
        or test "$PREVIOUS_MODLOADER" != "$MODLOADER"; \
        or test "$PREVIOUS_MODLOADER_VERSION" != "$MODLOADER_VERSION"
        echo "Minecraft version, modloader or modloader version have changed. Cleaning up..."
        cleanServerFiles
    end
end

echo "PREVIOUS_MINECRAFT_VERSION=$MINECRAFT_VERSION" >"./.previousrun"
echo "PREVIOUS_MODLOADER=$MODLOADER" >>"./.previousrun"
echo "PREVIOUS_MODLOADER_VERSION=$MODLOADER_VERSION" >>"./.previousrun"

switch $MODLOADER
    case "NeoForge"
        setupNeoForge
    case "Forge"
        setupForge
    case "Fabric"
        setupFabric
    case "Quilt"
        setupQuilt
    case "LegacyFabric"
        setupLegacyFabric
    case '*'
        crashServer "Incorrect modloader specified: $MODLOADER"
end

echo ""
if not test -s "eula.txt"
    echo "Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA."
    echo "Mojang's EULA is available to read at https://aka.ms/MinecraftEULA"
    echo "If you agree to Mojang's EULA then type 'I agree'"
    read -P "Response: " ANSWER

    if test "$ANSWER" = "I agree"
        echo "User agreed to Mojang's EULA."
        echo "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA)." >eula.txt
        echo "eula=true" >>eula.txt
    else
        crashServer "User did not agree to Mojang's EULA. Entered: $ANSWER. You can not run a Minecraft server unless you agree to Mojang's EULA."
    end
end

echo ""
echo "Starting server..."
echo "Minecraft version:              $MINECRAFT_VERSION"
echo "Modloader:                      $MODLOADER"
echo "Modloader version:              $MODLOADER_VERSION"
echo "LegacyFabric Installer Version: $LEGACYFABRIC_INSTALLER_VERSION"
echo "Fabric Installer Version:       $FABRIC_INSTALLER_VERSION"
echo "Quilt Installer Version:        $QUILT_INSTALLER_VERSION"
echo "Java Args:                      $JAVA_ARGS"
echo "Additional Args:                $ADDITIONAL_ARGS"
echo "SSJ Forge Args:                 $SSJ_FORGE_ARGS"
echo "Java Path:                      $JAVA"
echo "Wait For User Input:            $WAIT_FOR_USER_INPUT"
if test "$LAUNCHER_JAR_LOCATION" != "do_not_manually_edit"
    echo "Launcher JAR:                   $LAUNCHER_JAR_LOCATION"
end
echo "Run Command:       $JAVA $ADDITIONAL_ARGS $SERVER_RUN_COMMAND"
echo "Java version:"
"$JAVA" -version
echo ""

# Depending on $RESTART the server runs in a loop, to make sure it comes right back up after crashing.
while true
    runJavaCommand "$ADDITIONAL_ARGS $SERVER_RUN_COMMAND"
    # Captured immediately: the checks below run their own commands and would overwrite $status. The script exits with
    # this status, so a crashed server is distinguishable from a clean shutdown by anything reading the exit code.
    set -l server_exit_code $status
    if test "$SKIP_JAVA_CHECK" = "true"
        echo "Java version check was skipped. Did the server stop or crash because of a Java version mismatch?"
        echo "Detected $SEMANTICS[1].$SEMANTICS[2].$SEMANTICS[3] - Java $JAVA_VERSION, recommended $RECOMMENDED_JAVA_VERSION."
    end
    if test "$RESTART" != "true"
        echo "Exiting..."
        if test "$WAIT_FOR_USER_INPUT" = "true"
            pause
        end
        exit $server_exit_code
    end
    echo "Automatically restarting server in 5 seconds. Press CTRL + C to abort and exit."
    sleep 5
end
