::###############################################################################################
:: Copyright (C) 2025 Griefed
::
:: This script is free software; you can redistribute it and/or
:: modify it under the terms of the GNU Lesser General Public
:: License as published by the Free Software Foundation; either
:: version 2.1 of the License, or (at your option) any later version.
::
:: This library is distributed in the hope that it will be useful,
:: but WITHOUT ANY WARRANTY; without even the implied warranty of
:: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
:: Lesser General Public License for more details.
::
:: You should have received a copy of the GNU Lesser General Public
:: License along with this library; if not, write to the Free Software
:: Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
:: USA
::
:: The full license can be found at https:github.com/Griefed/ServerPackCreator/blob/main/LICENSE
::##############################################################################################
::
:: Start script generated by ServerPackCreator SPC_SERVERPACKCREATOR_VERSION_SPC.
:: The template which was used in the generation of this script can be found at:
::   https://github.com/Griefed/ServerPackCreator/blob/SPC_SERVERPACKCREATOR_VERSION_SPC/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.bat
::
:: This batch-script will run the start.ps1 script without you, the user, having to fiddle with admin-things.
:: Do not delete the PowerShell (.ps1) files or this script will stop working!
@ECHO OFF

PUSHD %~dp0

SET SCRIPTDIR=%~dp0
SET PSSCRIPTPATH=%SCRIPTDIR%start.ps1
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%PSSCRIPTPATH%' %1";