::###############################################################################################
:: Copyright (C) 2024  Griefed
::
:: This script is free software; you can redistribute it and/or
:: modify it under the terms of the GNU Lesser General Public
:: License as published by the Free Software Foundation; either
:: version 2.1 of the License, or (at your option) any later version.
::
:: This library is distributed in the hope that it will be useful,
:: but WITHOUT ANY WARRANTY; without even the implied warranty of
:: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
:: Lesser General Public License for more details.
::
:: You should have received a copy of the GNU Lesser General Public
:: License along with this library; if not, write to the Free Software
:: Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
:: USA
::
:: The full license can be found at https:github.com/Griefed/ServerPackCreator/blob/main/LICENSE
::##############################################################################################
::
:: Java Install script generated by ServerPackCreator SPC_SERVERPACKCREATOR_VERSION_SPC.
:: The template which was used in the generation of this script can be found at:
::   https://github.com/Griefed/ServerPackCreator/blob/SPC_SERVERPACKCREATOR_VERSION_SPC/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_java_template.ps1
::
:: Depending on which Minecraft version is used in this server pack, a different Java version may be installed.
::
:: ATTENTION:
::   This script will NOT modify the JAVA_HOME variable for your user.

IF NOT EXIST variables.txt (
    ECHO ERROR^^! variables.txt not present. Without it the server can not be installed, configured or started.
	EXIT 1
)


FOR /F "delims== tokens=1,2" %%G IN (variables.txt) DO (
	SET LINE=%%G
	IF NOT "%LINE:~0,1%"=="#" (
		SET %%G=%%H
	)
)


SET BACKSLASH=\
SET COLON=:
CALL SET JAVA=%%JAVA:\\=%BACKSLASH%%%
CALL SET JAVA=%%JAVA:\:=%COLON%%%


GOTO :START


:COMMANDAVAILABLE <COMMAND_TO_CHECK>
WHERE %~1 >nul 2>&1 && (
    EXIT /B 0
) || (
    EXIT /B 2
)

:INSTALLJABBA
ECHO Downloading and installing jabba.
CALL:COMMANDAVAILABLE "%JAVA%"
IF NOT ERRORLEVEL 0 (
	Write-Host "Downloading and installing jabba."
	PowerShell  ^
		[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ^
		Invoke-Expression ( ^
		Invoke-WebRequest "%JABBA_INSTALL_URL_PS%" -UseBasicParsing ^
		).Content
	%End PowerShell%
)


:START


CALL:COMMANDAVAILABLE "jabba"
IF NOT ERRORLEVEL 0 (
	ECHO Automated Java installation requires a piece of Software called 'Jabba'.
	ECHO Type 'I agree' if you agree to the installation of the aforementioned software.
	SET "EXPECT=I agree"
	SET /P "ANSWER=Answer: "

	IF !ANSWER!==!EXPECT! (
		CALL:INSTALLJABBA
	) ELSE (
		ECHO User did not agree to Jabba installation. Aborting Java installation process.
		EXIT 1
	)
)

ECHO Downloading and using Java %JDK_VENDOR%@%RECOMMENDED_JAVA_VERSION%
PowerShell  ^
	jabba install %JDK_VENDOR%@%RECOMMENDED_JAVA_VERSION% ^
	jabba use %JDK_VENDOR%@%RECOMMENDED_JAVA_VERSION%
%End PowerShell%

echo "Installation finished. Returning to start-script."