name: Create GitHub Pre-Release after GitLab tag mirror

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+'

jobs:
  preparations:
    runs-on: ubuntu-latest
    # OUTPUTS
    outputs:
      version: ${{ steps.tag.outputs.tag }}

    steps:
      # GET THE LATEST CODE
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # EXTRACT TAG FROM PUSH
      - name: Get tag
        id: tag
        uses: tj-actions/branch-names@v7.0.7
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

  jar-and-media:
    needs: preparations
    runs-on: ubuntu-latest

    steps:
      # GET THE LATEST CODE
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # BUILD PROJECT AND PUBLISH
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - uses: luangong/setup-install4j@v1
        with:
          version: 10.0.7
          license: ${{ secrets.INSTALL4J_LICENSE }}

      - name: Build release
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" generateLicenseReport --info --full-stacktrace
          ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" build --info --full-stacktrace -x :serverpackcreator-api:test -x :serverpackcreator-app:test
          ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" media --info --full-stacktrace -x :serverpackcreator-api:test -x :serverpackcreator-app:test

      # UPLOAD ARTIFACTS
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jar-media-build-artifacts
          path: |
            media
            serverpackcreator-api/build
            serverpackcreator-app/build
            serverpackcreator-web-frontend/dist
            serverpackcreator-plugin-example/build
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Rename JAR and Plugin
        run: |
          mv serverpackcreator-app/build/libs/serverpackcreator-app-${{ needs.preparations.outputs.version }}.jar serverpackcreator-app/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}.jar
          mv serverpackcreator-plugin-example/build/libs/serverpackcreator-plugin-example-${{ needs.preparations.outputs.version }}.jar serverpackcreator-plugin-example/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}-Example-Plugin.jar

      # UPLOAD ARTIFACTS
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: jar-media-release
          path: |
            media/*.dmg
            media/*.sh
            media/*.exe
            serverpackcreator-app/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}.jar
            serverpackcreator-plugin-example/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}-Example-Plugin.jar
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

  appimage:
    runs-on: ubuntu-latest
    needs: preparations
    steps:
      # GET THE LATEST CODE
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # BUILD PROJECT AND PUBLISH
      - name: Set up JDK 21
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Prepare
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" generateLicenseReport --info --full-stacktrace
          ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" build :serverpackcreator-app:copyDependencies :serverpackcreator-app:copyJar --info --full-stacktrace

      - name: Build Image
        run: |
          IFS="-" read -ra VERSION <<<"${{ needs.preparations.outputs.version }}"
          jpackage \
            --app-version "${VERSION[0]}" \
            --copyright "Copyright (C) 2024 Griefed" \
            --description "Create server packs from Minecraft Forge, NeoForge, Fabric, Quilt or LegacyFabric modpacks." \
            --dest serverpackcreator-app/build/dist \
            --icon serverpackcreator-app/jpackagerResources/app.png \
            --input serverpackcreator-app/build/jars \
            --java-options "-Dfile.encoding=UTF-8" \
            --java-options "-Dlog4j2.formatMsgNoLookups=true" \
            --main-class org.springframework.boot.loader.launch.JarLauncher \
            --main-jar serverpackcreator-app-${{ needs.preparations.outputs.version }}.jar \
            --name ServerPackCreator \
            --resource-dir serverpackcreator-app/jpackagerResources \
            --runtime-image $JAVA_HOME \
            --temp serverpackcreator-app/build/tmp/jpackager \
            --type "app-image" \
            --vendor "griefed.de" \
            --verbose

      - name: List
        run: ls -ahl serverpackcreator-app/build/dist

      - name: Create AppImage
        run: |
          mkdir -p serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/share/applications && \
          mkdir -p serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/icons/hicolor/512x512 && \
          mkdir -p serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/icons/hicolor/scalable && \
          cp -rf serverpackcreator-app/build/dist/ServerPackCreator/* \
                 serverpackcreator-app/build/dist/ServerPackCreator.AppDir && \
          cp serverpackcreator-app/jpackagerResources/appimage.desktop \
             serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/share/applications/ServerPackCreator.desktop && \
          cp serverpackcreator-app/jpackagerResources/appimage.png \
             serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/icons/hicolor/512x512/ServerPackCreator.png && \
          cp serverpackcreator-app/jpackagerResources/appimage.svg \
             serverpackcreator-app/build/dist/ServerPackCreator.AppDir/usr/icons/hicolor/scalable/ServerPackCreator.svg && \
          cd serverpackcreator-app/build/dist/ServerPackCreator.AppDir && \
            ln -s bin/ServerPackCreator \
                  AppRun && \
            ln -s usr/share/applications/ServerPackCreator.desktop \
                  ServerPackCreator.desktop && \
            ln -s usr/icons/hicolor/512x512/ServerPackCreator.png \
                  ServerPackCreator.png && \
            ln -s usr/icons/hicolor/scalable/ServerPackCreator.svg \
                  ServerPackCreator.svg && \
            cd .. && \
          curl \
            -L https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage \
            -o appimagetool.AppImage && \
          chmod +x appimagetool.AppImage && \
          ./appimagetool.AppImage --appimage-extract && \
          export PATH=./squashfs-root/usr/bin:${PATH} && \
          appimagetool \
            ServerPackCreator.AppDir \
            ServerPackCreator-${{ needs.preparations.outputs.version }}-Portable-Linux-x86_64.AppImage

      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: appimage-release
          path: |
            serverpackcreator-app/build/dist/ServerPackCreator-${{ needs.preparations.outputs.version }}-Portable-Linux-x86_64.AppImage
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

  prerelease:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [preparations, jar-and-media, appimage]

    steps:
      # GET THE LATEST CODE
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # GET RELEASE INFO
      - name: Get Release Info
        run: |
          curl --header \
          'PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}' \
          'https://git.griefed.de/api/v4/projects/63/releases/${{ needs.preparations.outputs.version }}' >> version.json

      # GET DESCRIPTION
      - name: Extract version changelog
        uses: sergeysova/jq-action@v2.3.0
        id: description
        with:
          cmd: "jq .description version.json -r | sed -e 's/\\n/\\n/g' > description.txt"
          multiline: true

      - name: General Pre-Info
        id: preinfo
        uses: jaywcjlove/github-action-read-file@v1.2.2
        with:
          path: misc/PRE-INFO.md

      - name: General Info
        id: info
        uses: jaywcjlove/github-action-read-file@v1.2.2
        with:
          path: misc/INFO.md

      - name: Dafuq # Otherwise we wouldn't be able to work with the file. Because reasons...
        run: sudo chown $USER description.txt

      - name: Check length and truncate if needed
        run: |
          if [[ $(wc -c description.txt | awk '{print $1}') -ge 8000 ]]; then
            truncate -s 8000 description.txt
            printf "\n\n............\n\nRelease notes truncated. For more details, see the [CHANGELOG](https://github.com/Griefed/ServerPackCreator/blob/${{ needs.preparations.outputs.version }}/CHANGELOG.md).\n\n" >> description.txt
          fi

      - name: Append Release Info
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: description.txt
          write-mode: append
          contents: |
            ${{ steps.preinfo.outputs.content }}
            ${{ steps.info.outputs.content }}

      - uses: actions/download-artifact@v4
        with:
          name: jar-media-release

      - uses: actions/download-artifact@v4
        with:
          name: appimage-release

      # GENERATE RELEASE
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.preparations.outputs.version }}
          name: Pre-Release ${{ needs.preparations.outputs.version }}
          body_path: description.txt
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          files: |
            media/*.dmg
            media/*.sh
            media/*.exe
            ServerPackCreator-${{ needs.preparations.outputs.version }}-Portable-Linux-x86_64.AppImage
            serverpackcreator-app/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}.jar
            serverpackcreator-plugin-example/build/libs/ServerPackCreator-${{ needs.preparations.outputs.version }}-Example-Plugin.jar

  news:
    runs-on: ubuntu-latest
    needs: [preparations, prerelease]

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Post WebHook Message
        run: |
          curl -L --output ./discord.sh https://raw.githubusercontent.com/ChaoticWeg/discord.sh/master/discord.sh
          chmod a+x ./discord.sh
          ./discord.sh \
            --webhook-url="${{ secrets.WEBHOOK_URL }}" \
            --username "$GITHUB_REPOSITORY" \
            --avatar "https://i.griefed.de/images/2020/11/18/Prosper_Docker_300x300.png" \
            --text "There's been a new pre-release for $GITHUB_REPOSITORY. The new version is ${{ needs.preparations.outputs.version }} and is available at <$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.preparations.outputs.version }}>" \
            --title "New $GITHUB_REPOSITORY Pre-Release" \
            --description "There's been a new release for $GITHUB_REPOSITORY. The new version is ${{ needs.preparations.outputs.version }} and is available at $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.preparations.outputs.version }}" \
            --color "0xC0FFEE" \
            --url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.preparations.outputs.version }}" \
            --author "Griefed" \
            --author-url "$GITHUB_SERVER_URL/Griefed" \
            --author-icon "https://i.griefed.de/images/2022/01/21/sam_1500x1500.th.jpg" \
            --thumbnail "https://i.griefed.de/images/2021/05/08/app.png" \
            --field "Author;[Griefed]($GITHUB_SERVER_URL/Griefed)" \
            --field "Platform;[GitHub]($GITHUB_SERVER_URL)" \
            --footer "Released at ${{ steps.date.outputs.today }}" \
            --footer-icon "https://i.griefed.de/images/2022/01/21/start_generation.png"