name: virustotal.yml

permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  virustotal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@936d8c5c00afe97d3d9a1af26d017cfdf26800a2 # v5
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            .jar$
            .sh$
            .dmg$
            .exe$