#!/usr/bin/with-contenv bash

if [ ! -f /data/serverpackcreator.conf ]; then
  echo "**** Setting up ServerPackCreator configuration. ****"
  cp -f \
    /defaults/serverpackcreator.conf \
    /data/serverpackcreator.conf
  sed -i \
    "s/MODPACKDIR/${MODPACKDIR}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/CLIENTMODS/${CLIENTMODS}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/COPYDIRS/${COPYDIRS}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/MINECRAFTVERSION/${MINECRAFTVERSION}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/MODLOADER/${MODLOADER}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/MODLOADERVERSION/${MODLOADERVERSION}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/INCLUDESERVERINSTALLATION/${INCLUDESERVERINSTALLATION}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/INCLUDESERVERICON/${INCLUDESERVERICON}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/INCLUDESERVERPROPERTIES/${INCLUDESERVERPROPERTIES}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/INCLUDESTARTSCRIPTS/${INCLUDESTARTSCRIPTS}/g" \
    /data/serverpackcreator.conf
  sed -i \
    "s/INCLUDEZIPCREATION/${INCLUDEZIPCREATION}/g" \
    /data/serverpackcreator.conf

  chown -R \
    abc:abc \
      /app/serverpackcreator \
      /data
fi

ln -sf /data /app/serverpackcreator

chown -R \
  abc:abc \
    /app/serverpackcreator \
    /data

echo "**** To reset the configuration, delete serverpackcreator.conf in /data and restart the container. ****"